// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $Envelope from "./islands/Envelope.tsx";
import * as $Hearts from "./islands/Hearts.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/Envelope.tsx": $Envelope,
    "./islands/Hearts.tsx": $Hearts,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
